### PR TITLE
Install geth on circleci

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
This ensures that any update to the geth package will not break installations. (At least on the CI)

**Comment by axic** [comment]
@karalabe @fjl @holiman any comments?

**Comment by holiman** [comment]
So how does this work? Will we get notified if it breaks on macos, is that the thing?

**Comment by axic** [comment]
It is a regular CI, Github displays the failure here.

**Comment by holiman** [comment]
Well then yes please, I guess?

**Pull request merged**
