### PR TITLE
Update cpp-ethereum brew for latest develop

### LINKED ISSUE #111: Mining on MacBookPro issue with cpp-ethereum
Hi All,

Running the following command failed:

$ brew reinstall cpp-ethereum --with-gpu-mining --devel --headless --build-from-source
Warning: Calling build.build_bottle? is deprecated!
Use build.bottle? instead.
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:37:in `reinstall_formula'

==> Reinstalling ethereum/ethereum/cpp-ethereum 
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --headless option so it will be ignored!
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --with-gpu-mining option so it will be ignored!
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/romanmagda/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/romanmagda/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
CMake Error in test/CMakeLists.txt:
  Target "web3jsonrpc" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "MHD_INCLUDE_DIR-NOTFOUND"

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    HAVE_CLOCK_GETTIME

-- Build files have been written to: /tmp/cpp-ethereum-20170526-16385-1f7a4yx

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

Please help me to solve the issue, thank you very much !

Roman

### PR DESCRIPTION
**Pull request by axic**
Fixes #111, #120, #121, #124, #126, #127, #129, #133 and #152.

### CODE REVIEW

**Comment by axic** [comment]
Not sure yet, submodule sync is stuck on the mac with the latest xcode :(

**Comment by axic** [comment]
It is failing with hunter:
```
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0-develop -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DVMTRACE=ON
-- [hunter] Initializing Hunter workspace (8f7cf6d719d05c49224a4ebeba90c6bb90b90f4a)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.20.9.tar.gz
-- [hunter]   -> /tmp/cpp-ethereum-20180321-73138-p0vv8r/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test fstack-protector-strong
-- Performing Test fstack-protector-strong - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- [hunter] Calculating Toolchain-SHA1

[hunter ** FATAL ERROR **] No toolchain info generated
[hunter ** FATAL ERROR **] [Directory:/tmp/cpp-ethereum-20180321-73138-p0vv8r/_3rdParty/Hunter/toolchain]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.no.toolchain.info
-------------------------------------------------------------------

CMake Error at /tmp/cpp-ethereum-20180321-73138-p0vv8r/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /tmp/cpp-ethereum-20180321-73138-p0vv8r/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  CMakeLists.txt:141 (hunter_fatal_error)



[hunter ** INTERNAL **] Generate failed: exit with code 1
[hunter ** INTERNAL **] [Directory:/tmp/cpp-ethereum-20180321-73138-p0vv8r]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180321-73138-p0vv8r/CMakeFiles/CMakeOutput.log".
```

**Comment by axic** [comment]
And here's with hunter debugging:
```
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0-develop -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DVMTRACE=ON -DHUNTER_STATUS_DEBUG=ON
-- [hunter *** DEBUG *** 2018-03-21T23:44:48] HUNTER_ROOT set using HOME environment variable
-- [hunter *** DEBUG *** 2018-03-21T23:44:48] HUNTER_ROOT: /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter
-- [hunter *** DEBUG *** 2018-03-21T23:44:48] Locking directory: /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d
-- [hunter *** DEBUG *** 2018-03-21T23:44:48] Lock done
-- [hunter *** DEBUG *** 2018-03-21T23:44:48] Run generate
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Build
-- [hunter] Initializing Hunter workspace (8f7cf6d719d05c49224a4ebeba90c6bb90b90f4a)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.20.9.tar.gz
-- [hunter]   -> /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d
Scanning dependencies of target Hunter
[ 12%] Creating directories for 'Hunter'
[ 25%] Performing download step (download, verify and extract) for 'Hunter'
-- Downloading...
   dst='/tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/v0.20.9.tar.gz'
   timeout='none'
-- Using src='https://github.com/ruslo/hunter/archive/v0.20.9.tar.gz'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='/tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/v0.20.9.tar.gz'
-- Downloading... done
-- extracting...
     src='/tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/v0.20.9.tar.gz'
     dst='/tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No patch step for 'Hunter'
[ 50%] No update step for 'Hunter'
[ 62%] No configure step for 'Hunter'
[ 75%] No build step for 'Hunter'
[ 87%] No install step for 'Hunter'
[100%] Completed 'Hunter'
[100%] Built target Hunter
-- [hunter *** DEBUG *** 2018-03-21T23:45:06] Finished
-- [hunter *** DEBUG *** 2018-03-21T23:45:06] Settings (initialize):
-- [hunter *** DEBUG *** 2018-03-21T23:45:06]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2018-03-21T23:45:06]   Cache init (NO)
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test fstack-protector-strong
-- Performing Test fstack-protector-strong - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- [hunter *** DEBUG *** 2018-03-21T23:45:12] Single-configuration generator
-- [hunter *** DEBUG *** 2018-03-21T23:45:12] List of cache servers:
-- [hunter *** DEBUG *** 2018-03-21T23:45:12]   * https://github.com/ethereum/hunter-cache
-- [hunter *** DEBUG *** 2018-03-21T23:45:12] Settings (finalize):
-- [hunter *** DEBUG *** 2018-03-21T23:45:12]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2018-03-21T23:45:12]   Cache init (NO)
-- [hunter *** DEBUG *** 2018-03-21T23:45:12] Variables from HunterGate:
-- [hunter *** DEBUG *** 2018-03-21T23:45:12]   HUNTER_GATE_ROOT: /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter
-- [hunter *** DEBUG *** 2018-03-21T23:45:12]   HUNTER_GATE_VERSION: 0.20.9
-- [hunter *** DEBUG *** 2018-03-21T23:45:12]   HUNTER_GATE_SHA1: 8f7cf6d719d05c49224a4ebeba90c6bb90b90f4a
-- [hunter] Calculating Toolchain-SHA1
-- [hunter *** DEBUG *** 2018-03-21T23:45:12] [/tmp/cpp-ethereum-20180321-76831-1gort1e/_3rdParty/Hunter/toolchain] > "/usr/local/Cellar/cmake/3.10.3/bin/cmake" "-DTOOLCHAIN_INFO_FILE=/tmp/cpp-ethereum-20180321-76831-1gort1e/_3rdParty/Hunter/toolchain/toolchain.info" "-DCMAKE_TOOLCHAIN_FILE=/tmp/cpp-ethereum-20180321-76831-1gort1e/cmake/toolchain.cmake" "-DHUNTER_SELF=/tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked" "-GUnix Makefiles" "-H/tmp/cpp-ethereum-20180321-76831-1gort1e/_3rdParty/Hunter/toolchain" "-B/tmp/cpp-ethereum-20180321-76831-1gort1e/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=/usr/local/Homebrew/Library/Homebrew/shims/super/gmake" "-DCMAKE_RELEASE_POSTFIX="
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

[hunter ** FATAL ERROR **] No toolchain info generated
[hunter ** FATAL ERROR **] [Directory:/tmp/cpp-ethereum-20180321-76831-1gort1e/_3rdParty/Hunter/toolchain]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.no.toolchain.info
-------------------------------------------------------------------

CMake Error at /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /tmp/cpp-ethereum-20180321-76831-1gort1e/.brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  CMakeLists.txt:141 (hunter_fatal_error)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180321-76831-1gort1e/_3rdParty/Hunter/toolchain/_builds/CMakeFiles/CMakeOutput.log".

[hunter ** INTERNAL **] Generate failed: exit with code 1
[hunter ** INTERNAL **] [Directory:/tmp/cpp-ethereum-20180321-76831-1gort1e]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:108 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:116 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_finalize.cmake:73 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.20.9/8f7cf6d/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:90 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20180321-76831-1gort1e/CMakeFiles/CMakeOutput.log".
```

**Comment by chfast** [comment]
Try suggestions for Homebrew in https://github.com/ruslo/hunter/wiki/error.no.toolchain.info.

**Pull request merged**
