### PR TITLE
Build aleth 1.4.0rc5 by default (unless --devel is selected)

### LINKED ISSUE #185: fatal: Remote branch develop not found in upstream origin
MacBook-Pro:alailson$ **brew install cpp-ethereum**
==> Installing cpp-ethereum from ethereum/ethereum
==> Installing dependencies for ethereum/ethereum/cpp-ethereum: cmake, gperftools, snappy, leveldb
.../...
==> Installing ethereum/ethereum/cpp-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/alailson/Library/Caches/Homebrew/cpp-ethereum--git'...

1. **warning: Could not find remote branch develop to clone.**
2. **fatal: Remote branch develop not found in upstream origin**
3. **Error: Failed to download resource "cpp-ethereum"**
4. **Failure while executing; `git clone --depth 1 --branch develop https://github.com/ethereum/cpp-ethereum.git /Users/alailson/Library/Caches/Homebrew/cpp-ethereum--git` exited with 128. Here's the output:**
5. Cloning into '/Users/alailson/Library/Caches/Homebrew/cpp-ethereum--git'...
6. warning: Could not find remote branch develop to clone.
7. **fatal: Remote branch develop not found in upstream origin**

**MAC OS H Sierra 10.13.6**

### PR DESCRIPTION
**Pull request by axic**
Fixes #185.

### CODE REVIEW

**Comment by chfast** [comment]
Can't it just download binaries from https://github.com/ethereum/aleth/releases/tag/v1.4.0rc5 ?

**Comment by axic** [comment]
> Can't it just download binaries from https://github.com/ethereum/aleth/releases/tag/v1.4.0rc5 ?

Do you have macos binaries there?

**Comment by chfast** [comment]
https://github.com/ethereum/aleth/releases/download/v1.4.0rc5/aleth-1.4.0rc5-darwin-x86_64.tar.gz

**Comment by axic** [comment]
Downloading binaries is a different process, called something like bottles, if we do that I would prefer to do it a separate PR.

**Comment by chfast** [comment]
Yes, sure.

Is there any documentation for this? I have absolutely no way of testing homebrew.

**Comment by axic** [comment]
https://docs.brew.sh/Bottles

It is not clear where to put the built binaries though.

**Comment by chfast** [comment]
It will not, because you have to build it with homebrew first to bottle it.

**Comment by axic** [comment]
Then it is definitely not worth spending time on it now.

**Pull request merged**
