### PR TITLE
Require el capitan for geth

### LINKED ISSUE #117: Error installing go-ethereum on Mac OS X
Mac OS X (10.10.5)
gcc version 7.0.2
go version 1.8.3

**When installing using Homebrew:**

$ brew install ethereum --devel
==> Installing ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/go-ethereum.git
Updating /Users/piotrgrudzien/Library/Caches/Homebrew/ethereum--git
==> Checking out branch master
==> go env
==> make all
Last 15 lines from /Users/piotrgrudzien/Library/Logs/Homebrew/ethereum/02.make:
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/elgamal
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/s2k
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp/packet
github.com/ethereum/go-ethereum/vendor/github.com/docker/docker/pkg/reexec
github.com/ethereum/go-ethereum/internal/cmdtest
github.com/ethereum/go-ethereum/internal/guide
github.com/ethereum/go-ethereum/tests
github.com/ethereum/go-ethereum/whisper/shhclient
github.com/ethereum/go-ethereum/vendor/github.com/Azure/azure-storage-go
github.com/ethereum/go-ethereum/whisper/whisperv2
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/openpgp
github.com/ethereum/go-ethereum/internal/build
util.go:44: exit status 2
exit status 1
make: *** [all] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Install all go-ethereum executables https://github.com/ethereum/homebrew-ethereum/pull/114
Unable to install go-ethereum  https://github.com/ethereum/homebrew-ethereum/issues/89
Error during install of  cpp-ethereum ([ 22%] Built target llvm make: *** [all] Error 2) https://github.com/ethereum/homebrew-ethereum/issues/116

**When building from source:**

$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
\>>> /usr/local/Cellar/go/1.8.3/libexec/bin/go install -ldflags -X main.gitCommit=0ff35e170d1b913082313089d13e3e6d5490839b -s -v ./cmd/geth
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
 github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
In file included from vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:10:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:43:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UTCUtils.h:22:10: fatal error: 'CarbonCore/MacErrors.h' file not found
#include <CarbonCore/MacErrors.h>
         ^
1 error generated.
util.go:44: exit status 2
exit status 1
make: *** [geth] Error 1

### PR DESCRIPTION
**Pull request by axic**
Fixes #117, #131 and #132.

I think this fixes the build problems - requires xcode (HID framework) and new macos.

### CODE REVIEW

**Comment by axic** [comment]
@karalabe can this be merged?

**Comment by karalabe** [comment]
I never in my life owned a macos machine. I don't know.

**Comment by fjl** [comment]
Requiring XCode is not nice. I think CLT should be sufficient. I can build go-ethereum with CLT without issues.

**Comment by axic** [comment]
> Requiring XCode is not nice.

I haven't found a way to require those framework dependencies are installed otherwise. They are required by @karalabe's HID library.

**Comment by fjl** [comment]
What version of macOS are you using?

**Pull request merged**
