### PR TITLE
[WIP] Update circleCI to handle multiple formula

### PR DESCRIPTION
**Pull request by ChrisChinchilla**

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@chriseth and @axic And I'm not sure CircleCI is running, but this _should_ allow for testing…

**Comment by chriseth** [comment]
Circle did not run. Please try rebasing onto master.

**Comment by ChrisChinchilla** [comment]
This was based on a branch that was based on master, but redone. I'm not seeing Circle results anywhere, is it because it's from my own fork?

**Comment by chriseth** [comment]
Ah yes, that might be.

**Comment by ChrisChinchilla** [comment]
Closing in favour of https://github.com/ethereum/homebrew-ethereum/pull/221

**Pull request closed without merging**
