### PR TITLE
Install swarm commands

### PR DESCRIPTION
**Pull request by axic**
Fixes https://github.com/ethereum/go-ethereum/issues/3395.

### CODE REVIEW

**Comment by axic** [comment]
Must update this to install `swarm` instead.

**Comment by axic** [comment]
@zelig is this ok to merge?

**Comment by axic** [comment]
@karalabe any chance of merging this?

**Comment by karalabe** [comment]
Hmm, so `swarm` conflicts on Ubuntu with an official package. There have been talks for a while now whether to rename it to something else. I'm all for installing swarm, but maybe we should pick the final name first.

@zelig @gbalint ?

**Comment by axic** [comment]
Oh I wasn't aware of that. Too bad, hope this can resolved "soon" :)

**Comment by axic** [comment]
Apparently the `geth` brew does this: https://github.com/Homebrew/homebrew-core/blob/master/Formula/geth.rb#L19

**Comment by gbalint** [comment]
@karalabe We have been planning to rename the ubuntu package for a while, then we will schedule to do it as soon as possible. Here is our issue: https://github.com/ethersphere/go-ethereum/issues/191

**Comment by axic** [comment]
@karalabe @fjl this should address the problem, making `swarm` an optional installation so it shouldn't conflict with any other package, unless requested by the user

**Comment by axic** [comment]
Also rebased to remove the conflict.

**Comment by axic** [comment]
Also note that the `geth` package in homebrew just installs everything: https://github.com/Homebrew/homebrew-core/blob/master/Formula/geth.rb#L17-L20

**Comment by axic** [comment]
Closing this is long overdue (merging would have been better), but Swarm is not part of the geth repository anymore. It is located here now: https://github.com/ethersphere/swarm

**Pull request closed without merging**
