### PR TITLE
Update cpp-ethereum formula

### PR DESCRIPTION
**Pull request by chfast**
- Remove cryptopp dependency.
- Remove "paranoia" deprecated option.

### CODE REVIEW

**Comment by chfast** [comment]
Can this be tested?

**Comment by chriseth** [comment]
Not sure.

**Comment by pirapira** [comment]
I think I can.

**Comment by pirapira** [comment]
It seems working (now Homebrew is doing `make`).  I replaced `/usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb` with the new content, and `brew install cpp-ethereum` does not draw `cryptopp` anymore.

**Comment by chfast** [comment]
Ok, thanks!

**Pull request merged**
