### PR TITLE
Solidity 0.7.5

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by axic** [comment]
Tests fail with:
```
Error: Calling Installation of solidity from a GitHub commit URL is disabled! Use 'brew extract solidity' to stable tap on GitHub instead.
```

What did homebrew did again?

**Comment by chriseth** [comment]
It was like that for several releases now. I actually don't know if this is working, but at least the "official" homebrew repo works.

**Comment by axic** [comment]
> It was like that for several releases now. I actually don't know if this is working,

It seems y'all are merging this broken since September 😅 

Probably they disallowed installing from direct URL.

> but at least the "official" homebrew repo works.

What do you mean?

**Comment by chriseth** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/solidity.rb

**Pull request merged**
