### PR TITLE
Updated Homebrew paths to new repository.

### PR DESCRIPTION
**Pull request by bobsummerwill**
Homebrew is currently broken.   This should get it healthier, and we can iterate from there.

### CODE REVIEW

**Comment by alailsonribeiro** [comment]
MacBook-Pro:alailson$ **brew install cpp-ethereum**
==> Installing cpp-ethereum from ethereum/ethereum
==> Installing dependencies for ethereum/ethereum/cpp-ethereum: cmake, gperftools, snappy, leveldb
.../...
==> Installing ethereum/ethereum/cpp-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/alailson/Library/Caches/Homebrew/cpp-ethereum--git'...

1. **warning: Could not find remote branch develop to clone.**
2. **fatal: Remote branch develop not found in upstream origin**
3. **Error: Failed to download resource "cpp-ethereum"**
4. **Failure while executing; `git clone --depth 1 --branch develop https://github.com/ethereum/cpp-ethereum.git /Users/alailson/Library/Caches/Homebrew/cpp-ethereum--git` exited with 128. Here's the output:**
5. Cloning into '/Users/alailson/Library/Caches/Homebrew/cpp-ethereum--git'...
6. warning: Could not find remote branch develop to clone.
7. **fatal: Remote branch develop not found in upstream origin**

Could you help me ?

**Comment by bobsummerwill** [comment]
I don't believe the Homebrew is being maintained anymore, eh, @axic?

Should probably be deleted if so.

**Comment by axic** [comment]
It is somewhat maintained, this particular issue has been fixed now. However it doesn't compile for months due to an issue between homebrew and hunter :)

**Comment by bobsummerwill** [comment]
Fun times, @axic!

**Pull request merged**
